proto/domain.thrift

https://rbkmoney.atlassian.net/browse/BJ-844

BJ-844: Cash register provider

---

proto/domain.thrift

Кажется, что именно этой структуры не хватает

PROX-413: add Proxy

---

proto/claim_management.thrift

https://rbkmoney.atlassian.net/browse/BJ-910

BJ-910: Search claims by email

---

proto/merch_stat.thrift

https://rbkmoney.atlassian.net/browse/BJ-925

BJ-925: Add external_id in merch_stat

---

proto/domain.thrift
proto/domain_config.thrift

Важный момент: появляется возможность ввести цикл в граф объектов domain config, и об этом надо помнить клиентам. Есть мысль быть пессимистичным и требовать отсутствие циклов в рамках коммита, что потребует PR в rbkmoney/dmt_core.

DC-120: Introduce 'criteria' as means to reuse complex conditions

---

proto/payout_processing.thrift

https://rbkmoney.atlassian.net/browse/BJ-937
По аналогии с Invoicing.GetEvents()

BJ-937: Add method to get events by payoutID

---

proto/domain_config.thrift

In line with rbkmoney/dmt_core#20.

DC-120: Fix domain_config.Commit exception interface

---

proto/payment_processing.thrift

Thought of using a boolean parameter but decided to make it more expandable just in case.

HG-542: chargebacks, skip stage

---

proto/domain.thrift

It is a Brazilian card association. We already have operations with their cards in our storage.

MSPF-560 Add ELO payment system

---

proto/payment_processing.thrift

Кажется Timestamp тут не нужен, а обратную совместимость все равно ломаем, так что выпилил

HG-555: Refactor ComputeShopTerms

---

proto/payment_tool_token.thrift

Добавлена новая  структура  платежного токена (PaymentToolToken)  с поддержкой времни жизни токена.

CAPI-427: gap for able to expire payment tokens

---

proto/domain.thrift

HG-562: Move short_payment_id to AdditionalTransactionInfo

---

proto/payment_processing.thrift
proto/payment_tool_provider.thrift

Добавляем expiry_date для Apple Pay, Google Pay и Samsung Pay провайдеров

Provider expiry date

---

proto/domain.thrift
proto/merch_stat.thrift

https://rbkmoney.atlassian.net/browse/PLANTEAM-994

PLANTEAM-994: Add RBS terminal

---

proto/payment_processing.thrift

- fix: Fix formatting
- ED-94/feat: Add customer_id
- ED-92/feat: Add template_id

ED 92+ED 94/feat/capi id generation

---

proto/payment_processing.thrift

См. https://rbkmoney.atlassian.net/browse/ED-95

ED-95/feat: Switch proto defs to required ids

---

proto/payment_processing.thrift

Заметил ещё пару мест, где это имеет смысл сделать:
1. InvoiceParams: https://github.com/rbkmoney/erlang_capi_v2/blob/master/apps/capi/src/capi_handler_invoices.erl#L295-L296
2. InvoiceWithTemplateParams: https://github.com/rbkmoney/erlang_capi_v2/blob/master/apps/capi/src/capi_handler_invoice_templates.erl#L289-L290

Ed 95/feat/id passing proto switch

---

proto/domain.thrift

Заметка по именованию: https://en.wikipedia.org/wiki/Trade_bloc

ED-148/feat: Add geo info to int. legal entity

---

proto/domain.thrift

Alos leave note about allocations in refunds.

Add basic allocations service terms

---

proto/domain.thrift

BUSINESS-160: Rename `allowed` → `allow` in terms

---

proto/merch_stat.thrift

новый формат статистики выводов. отедельная ветка для устранения блокировки со сплитами. 
refs: #JD-477 #688

ED-194: new payouts

---

proto/merch_stat.thrift

Правка в эпике, т.к в текущем мастере был добавлен [PaymentInstitutionAccount](https://github.com/rbkmoney/damsel/blob/34a0652bc5d8549f302ed95d02bdd2cbc7d4f315/proto/domain.thrift#L897), который тянет за собой необходимость внесения более комплексных изменений на стороне приложений (magista).

JD-525: Added separate method for getting refunds stat

---

proto/payment_processing.thrift

See:
- #715
- https://github.com/rbkmoney/swag/pull/447#discussion_r705355939

ED-261/fix: Make InvoiceTemplateCreateParams.name optional
